"""added skills and achieves fields

Revision ID: 08c4c45c8669
Revises: 9b28172b282e
Create Date: 2026-07-11 19:46:30.106216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08c4c45c8669'
down_revision: Union[str, Sequence[str], None] = '9b28172b282e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('projects', sa.Column('achievements', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('projects', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'achievements')
    op.drop_column('projects', 'skills')
    # ### end Alembic commands ###
