"""added_website_url

Revision ID: 09e9e24aa7c2
Revises: h5c6d7e8f9a2
Create Date: 2026-07-06 21:33:34.460638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '09e9e24aa7c2'
down_revision: Union[str, Sequence[str], None] = 'h5c6d7e8f9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_parsed_jobs', sa.Column('web_site', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_parsed_jobs', 'web_site')
    # ### end Alembic commands ###
