"""Make auto parsing job nullable

Revision ID: 1da5b87532d0
Revises: 08c4c45c8669
Create Date: 2026-07-20 17:21:02.391963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da5b87532d0'
down_revision: Union[str, Sequence[str], None] = '08c4c45c8669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_parsed_jobs', 'parsing_job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_parsed_jobs', 'parsing_job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
