"""added_gin_index_project_model

Revision ID: 38882cd758f0
Revises: 09e9e24aa7c2
Create Date: 2026-07-11 16:27:33.913497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38882cd758f0'
down_revision: Union[str, Sequence[str], None] = '09e9e24aa7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_projects_technologies_gin', 'projects', ['technologies'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_technologies_gin', table_name='projects', postgresql_using='gin')
    # ### end Alembic commands ###
