"""Make AutoParsedJob.vacancy_id nullable

Revision ID: d9c8149460e0
Revises: 1da5b87532d0
Create Date: 2026-07-20 17:34:52.122546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c8149460e0'
down_revision: Union[str, Sequence[str], None] = '1da5b87532d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_parsed_jobs', 'vacancy_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_parsed_jobs', 'vacancy_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
