import { Badge, Box, Button, Flex, Heading, Input, Select, Spinner, Stack, Switch, Text, useDisclosure } from '@chakra-ui/react';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ConstructorTabs } from '@/features/letter-constructor/components/ConstructorTabs';
import { PhraseFormModal } from '@/features/letter-constructor/components/PhraseFormModal';
import { letterConstructorApi } from '@/features/letter-constructor/api';
import { useConstructorMutation, useDebouncedValue, usePhrases } from '@/features/letter-constructor/hooks';
import type { LetterPhrase, PhraseType } from '@/features/letter-constructor/types';

const types: PhraseType[] = ['opening','experience_bridge','portfolio_intro','stack_summary','closing','custom'];
export default function LetterPhrasesPage() {
  const [q,setQ]=useState(''); const [type,setType]=useState<PhraseType|undefined>(); const [active,setActive]=useState(''); const [page,setPage]=useState(1); const [editingPhrase,setEditingPhrase]=useState<LetterPhrase>(); const modal=useDisclosure();
  const { t } = useTranslation();
  const query=usePhrases({q:useDebouncedValue(q)||undefined,type,is_active:active===''?undefined:active==='true',page,page_size:20});
  const remove=useConstructorMutation<number>((id)=>letterConstructorApi.deletePhrase(id));
  const openForm=(phrase?:LetterPhrase)=>{setEditingPhrase(phrase);modal.onOpen()};
  return <Box><ConstructorTabs/><Flex justify="space-between" mb={5}><Heading size="lg">{t('letterConstructor.phrases.title')}</Heading><Button colorScheme="purple" onClick={()=>openForm()}>{t('letterConstructor.phrases.new')}</Button></Flex><Flex gap={3} mb={5} wrap="wrap"><Input maxW="360px" placeholder={t('letterConstructor.common.search')} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><Select maxW="230px" value={type||''} onChange={e=>setType((e.target.value||undefined) as PhraseType|undefined)}><option value="">{t('letterConstructor.phrases.allTypes')}</option>{types.map(v=><option key={v}>{v}</option>)}</Select><Select maxW="180px" value={active} onChange={e=>setActive(e.target.value)}><option value="">{t('letterConstructor.phrases.anyStatus')}</option><option value="true">{t('letterConstructor.phrases.active')}</option><option value="false">{t('letterConstructor.phrases.inactive')}</option></Select></Flex>{query.isLoading&&<Spinner/>}<Stack>{query.data?.items.map(p=><Box key={p.id} bg="surface.raised" borderRadius="xl" p={4}><Flex justify="space-between" gap={4}><Box><Badge>{p.type}</Badge><Text mt={2}>{p.text}</Text><Text fontSize="xs" color="text.muted">{t('letterConstructor.phrases.used',{count:p.used_in_templates})}</Text></Box><Flex gap={2} align="center"><Switch isChecked={p.is_active} onChange={()=>letterConstructorApi.updatePhrase(p.id,{is_active:!p.is_active}).then(()=>query.refetch())}/><Button size="sm" onClick={()=>openForm(p)}>{t('letterConstructor.common.edit')}</Button><Button size="sm" variant="danger" isDisabled={p.used_in_templates>0} onClick={()=>window.confirm(t('letterConstructor.phrases.deleteConfirm'))&&remove.mutate(p.id)}>{t('letterConstructor.common.delete')}</Button></Flex></Flex></Box>)}</Stack><Flex mt={5} gap={3}><Button isDisabled={page===1} onClick={()=>setPage(page-1)}>{t('letterConstructor.common.back')}</Button><Text pt={2}>{page}</Text><Button isDisabled={!query.data||page*20>=query.data.total} onClick={()=>setPage(page+1)}>{t('letterConstructor.common.next')}</Button></Flex><PhraseFormModal isOpen={modal.isOpen} phrase={editingPhrase} onClose={modal.onClose} onSaved={async()=>{await query.refetch()}}/></Box>;
}
